export const FETCH_RECEIPT = 'FETCH_RECEIPT';
export const FETCH_RECEIPT_SUCCESS = 'FETCH_RECEIPT_SUCCESS';
export const FETCH_RECEIPT_FAILED = 'FETCH_RECEIPT_FAILED';

export const FILTER_RECEIPT = 'FILTER_RECEIPT';
export const FILTER_RECEIPT_SUCCESS = 'FILTER_RECEIPT_SUCCESS';
export const FILTER_RECEIPT_FAILED = 'FILTER_RECEIPT_FAILED';

export const ADD_RECEIPT = 'ADD_RECEIPT';
export const ADD_RECEIPT_SUCCESS = 'ADD_RECEIPT_SUCCESS';
export const ADD_RECEIPT_FAILED = 'ADD_RECEIPT_FAILED';
export const REDIRECT_AFTER_ADD_SUCCESS = '/receipt-info/:id';

export const SET_RECEIPT_EDITTING = 'SET_RECEIPT_EDITTING';
export const RESET_RECEIPT_EDITTING = 'RESET_RECEIPT_EDITTING';

export const UPDATE_RECEIPT = 'UPDATE_RECEIPT';
export const UPDATE_RECEIPT_SUCCESS = 'UPDATE_RECEIPT_SUCCESS';
export const UPDATE_RECEIPT_FAILED = 'UPDATE_RECEIPT_FAILED';

export const DELETE_RECEIPT = 'DELETE_RECEIPT';
export const DELETE_RECEIPT_SUCCESS = 'DELETE_RECEIPT_SUCCESS';
export const DELETE_RECEIPT_FAILED = 'DELETE_RECEIPT_FAILED';

export const FETCH_SUPPLIER = 'FETCH_SUPPLIER';
export const FETCH_SUPPLIER_SUCCESS = 'FETCH_SUPPLIER_SUCCESS';
export const FETCH_SUPPLIER_FAILED = 'FETCH_SUPPLIER_FAILED';

export const FETCH_VARIANT = 'FETCH_VARIANT';
export const FETCH_VARIANT_SUCCESS = 'FETCH_VARIANT_SUCCESS';
export const FETCH_VARIANT_FAILED = 'FETCH_VARIANT_FAILED';

export const FETCH_RECEIPT_ONE = 'FETCH_RECEIPT_ONE';
export const FETCH_RECEIPT_ONE_SUCCESS = 'FETCH_RECEIPT_ONE_SUCCESS';
export const FETCH_RECEIPT_ONE_FAILED = 'FETCH_RECEIPT_ONE_FAILED';

export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
export const UPDATE_PAYMENT_FAILED = 'UPDATE_PAYMENT_FAILED';

export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILED = 'UPDATE_STATUS_FAILED';

export const SEARCH_RECEIPT = 'SEARCH_RECEIPT';
export const SEARCH_RECEIPT_SUCCESS = 'SEARCH_RECEIPT_SUCCESS';
export const SEARCH_RECEIPT_FAILED = 'SEARCH_RECEIPT_FAILED';

export const EDIT_RECEIPT = 'EDIT_RECEIPT';
export const EDIT_RECEIPT_SUCCESS = 'EDIT_RECEIPT_SUCCESS';
export const EDIT_RECEIPT_FAILED = 'EDIT_RECEIPT_FAILED';

export const UPDATE_TAG = 'UPDATE_TAG';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILED = 'UPDATE_TAG_FAILED';

export const ADD_SUPPLIER_RECEIPT = 'ADD_SUPPLIER_RECEIPT';
export const ADD_SUPPLIER_RECEIPT_SUCCESS = 'ADD_SUPPLIER_RECEIPT_SUCCESS';
export const ADD_SUPPLIER_RECEIPT_FAILED = 'ADD_SUPPLIER_RECEIPT_FAILED';
