export const FETCH_SUPPLIER = 'FETCH_SUPPLIER';
export const FETCH_SUPPLIER_BY_PAGE_SIZE = 'FETCH_SUPPLIER_BY_PAGE_SIZE';
export const FETCH_SUPPLIER_BY_PAGE_SIZE_SUS = 'FETCH_SUPPLIER_BY_PAGE_SIZE_SUS';
export const FETCH_SUPPLIER_BY_PAGE_SIZE_FAI = 'FETCH_SUPPLIER_BY_PAGE_SIZE_FAI';
export const FETCH_SUPPLIER_SUCCESS = 'FETCH_SUPPLIER_SUCCESS';
export const FETCH_SUPPLIER_FAILED = 'FETCH_SUPPLIER_FAILED';
export const FETCH_TOTAL_ITEM = 'FETCH_TOTAL_ITEM';

export const FILTER_SUPPLIER = 'FILTER_SUPPLIER';
export const FILTER_SUPPLIER_SUCCESS = 'FILTER_SUPPLIER_SUCCESS';
export const FILTER_SUPPLIER_FAILED = 'FILTER_SUPPLIER_FAILED';

export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_FAILED = 'ADD_SUPPLIER_FAILED';
export const REDIRECT_AFTER_ADD_SUCCESS = '/supplier-info/:id';

export const SET_SUPPLIER_EDITTING = 'SET_SUPPLIER_EDITTING';
export const RESET_SUPPLIER_EDITTING = 'RESET_SUPPLIER_EDITTING';

export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAILED = 'UPDATE_SUPPLIER_FAILED';

export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAILED = 'DELETE_SUPPLIER_FAILED';

export const FETCH_SUPPLIER_ONE = 'FETCH_SUPPLIER_ONE';
export const FETCH_SUPPLIER_ONE_SUCCESS = 'FETCH_SUPPLIER_ONE_SUCCESS';
export const FETCH_SUPPLIER_ONE_FAILED = 'FETCH_SUPPLIER_ONE_FAILED';

/************* */
export const SEARCH_SUPPLIER = 'SEARCH_SUPPLIER';
export const SEARCH_SUPPLIER_SUCCESS = 'SEARCH_SUPPLIER_SUCCESS';
export const SEARCH_SUPPLIER_FAILED = 'SEARCH_SUPPLIER_FAILED';